package com.example.weathernow.presentation.util

import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.compositionLocalOf
import com.example.weathernow.domain.model.AppLanguage

data class AppStringResources(
    val appName: String,
    val navHome: String,
    val navSearch: String,
    val navFavorites: String,
    val navSettings: String,
    val currentPosition: String,
    val locating: String,
    val unableToLoadWeather: String,
    val locationPermissionRequired: String,
    val locationUnavailable: String,
    val genericLocationFailure: String,
    val genericSearchFailure: String,
    val error: String,
    val retrySync: String,
    val updatedJustNow: String,
    val updatedAgo: (String) -> String,
    val offlineBanner: String,
    val retry: String,
    val searchPlaceholder: String,
    val searchLocation: String,
    val noWeatherDataTitle: String,
    val noWeatherDataSubtitle: String,
    val useMyLocation: String,
    val popularCities: String,
    val recentSearches: String,
    val clearAll: String,
    val noRecentSearches: String,
    val favoriteLocations: String,
    val pinnedCurrentLocation: String,
    val addLocation: String,
    val noFavoritesTitle: String,
    val noFavoritesSubtitle: String,
    val feelsLike: (Int) -> String,
    val feelsLikeLabel: String,
    val humidity: String,
    val windSpeed: String,
    val uvIndex: String,
    val precipitation: String,
    val forecast24h: String,
    val forecast7d: String,
    val settingsTitle: String,
    val languageSection: String,
    val unitsAppearanceSection: String,
    val themeMode: String,
    val themeSystem: String,
    val themeLight: String,
    val themeDark: String,
    val temperatureUnit: String,
    val windUnit: String,
    val updatesNotificationsSection: String,
    val dailySummary: String,
    val dailySummaryDesc: String,
    val severeAlerts: String,
    val severeAlertsDesc: String,
    val backgroundRefresh: String,
    val backgroundRefreshDesc: String,
    val offlineStorageSection: String,
    val offlineCache: String,
    val clearCache: String,
    val clearCacheSuccess: String,
    val aboutSection: String,
    val weatherProvider: String,
    val appVersion: String,
    val forecastDetailTitle: (String) -> String,
    val forecastSubtitle: String,
    val liveTrend: String,
    val sunMoonCycle: String,
    val sunrise: String,
    val solarNoon: String,
    val sunset: String,
    val pressure: String,
    val visibility: String,
    val humidityDew: String,
    val windGusts: String,
    val expectedToday: String,
    val moderate: String,
    val high: String,
    val normal: String,
    val standardPressure: String,
    val clearAtmosphere: String,
    val thermalComfort: String,
    val moderateProtection: String,
    val dewPointLabel: (Int) -> String,
    val windDirectionLabel: (Int) -> String
)

val EnglishStrings = AppStringResources(
    appName = "WeatherNow",
    navHome = "Home",
    navSearch = "Search",
    navFavorites = "Favorites",
    navSettings = "Settings",
    currentPosition = "Current Location",
    locating = "Locating…",
    unableToLoadWeather = "Unable to Load Weather",
    locationPermissionRequired = "Location permission is required to use this feature",
    locationUnavailable = "Unable to obtain device location. Try searching manually.",
    genericLocationFailure = "Unable to obtain device location. Please try again.",
    genericSearchFailure = "Unable to search locations. Please try again.",
    error = "Error",
    retrySync = "Retry Sync",
    updatedJustNow = "Updated just now",
    updatedAgo = { time -> "Updated $time ago" },
    offlineBanner = "Offline mode. Showing cached data from",
    retry = "Retry",
    searchPlaceholder = "Search city or country (e.g. Hanoi, Tokyo)...",
    searchLocation = "Search Location",
    noWeatherDataTitle = "No Weather Data",
    noWeatherDataSubtitle = "Search for a city or turn on location services.",
    useMyLocation = "Use My Location",
    popularCities = "Popular Cities",
    recentSearches = "Recent Searches",
    clearAll = "Clear all",
    noRecentSearches = "No recent searches yet",
    favoriteLocations = "Favorite Locations",
    pinnedCurrentLocation = "Current Location",
    addLocation = "Add Location",
    noFavoritesTitle = "No Favorite Cities Added",
    noFavoritesSubtitle = "Keep track of weather in your favorite destinations by tapping Add Location.",
    feelsLike = { temp -> "Feels like $temp°C" },
    feelsLikeLabel = "Feels Like",
    humidity = "Humidity",
    windSpeed = "Wind Speed",
    uvIndex = "UV Index",
    precipitation = "Precipitation",
    forecast24h = "24-Hour Forecast",
    forecast7d = "7-Day Forecast",
    settingsTitle = "Settings",
    languageSection = "Language / Ngôn ngữ",
    unitsAppearanceSection = "Units & Appearance",
    themeMode = "Theme Mode",
    themeSystem = "System",
    themeLight = "Light",
    themeDark = "Dark",
    temperatureUnit = "Temperature Unit",
    windUnit = "Wind Speed Unit",
    updatesNotificationsSection = "Updates & Notifications",
    dailySummary = "Daily Weather Summary",
    dailySummaryDesc = "Receive a morning briefing at 07:00 AM",
    severeAlerts = "Severe Weather Alerts",
    severeAlertsDesc = "Immediate push alerts for storms and high UV",
    backgroundRefresh = "Background Weather Refresh",
    backgroundRefreshDesc = "Periodically sync weather in background",
    offlineStorageSection = "Data & Offline Storage",
    offlineCache = "Offline Weather Cache",
    clearCache = "Clear Cache",
    clearCacheSuccess = "Cache cleared successfully",
    aboutSection = "About WeatherNow",
    weatherProvider = "Weather Data Provider",
    appVersion = "Application Version",
    forecastDetailTitle = { location -> "$location — Forecast & Trends" },
    forecastSubtitle = "Forecast & Trends",
    liveTrend = "Live Trend",
    sunMoonCycle = "Sun & Moon Horizon Cycle",
    sunrise = "Sunrise",
    solarNoon = "Solar Noon",
    sunset = "Sunset",
    pressure = "Pressure",
    visibility = "Visibility",
    humidityDew = "Humidity & Dew",
    windGusts = "Wind & Gusts",
    expectedToday = "Expected today",
    moderate = "Moderate",
    high = "High",
    normal = "Normal",
    standardPressure = "Standard pressure",
    clearAtmosphere = "Clear atmosphere",
    thermalComfort = "Normal thermal comfort",
    moderateProtection = "Moderate protection",
    dewPointLabel = { temp -> "Dew point: $temp°C" },
    windDirectionLabel = { deg -> "Direction: $deg° East" }
)

val VietnameseStrings = AppStringResources(
    appName = "WeatherNow",
    navHome = "Trang chủ",
    navSearch = "Tìm kiếm",
    navFavorites = "Yêu thích",
    navSettings = "Cài đặt",
    currentPosition = "Vị trí hiện tại",
    locating = "Đang định vị…",
    unableToLoadWeather = "Không thể tải dữ liệu thời tiết",
    locationPermissionRequired = "Cần cấp quyền vị trí để sử dụng tính năng này",
    locationUnavailable = "Không thể xác định vị trí. Hãy thử tìm kiếm thủ công.",
    genericLocationFailure = "Không thể xác định vị trí. Vui lòng thử lại.",
    genericSearchFailure = "Không thể tìm kiếm địa điểm. Vui lòng thử lại.",
    error = "Lỗi",
    retrySync = "Thử đồng bộ lại",
    updatedJustNow = "Vừa cập nhật",
    updatedAgo = { time -> "Cập nhật $time trước" },
    offlineBanner = "Chế độ ngoại tuyến. Dữ liệu lưu từ",
    retry = "Thử lại",
    searchPlaceholder = "Tìm kiếm thành phố hoặc quốc gia (vd: Hà Nội, Tokyo)...",
    searchLocation = "Tìm kiếm địa điểm",
    noWeatherDataTitle = "Chưa có dữ liệu thời tiết",
    noWeatherDataSubtitle = "Tìm kiếm thành phố hoặc bật định vị vị trí.",
    useMyLocation = "Vị trí của tôi",
    popularCities = "Thành phố phổ biến",
    recentSearches = "Tìm kiếm gần đây",
    clearAll = "Xóa tất cả",
    noRecentSearches = "Chưa có lịch sử tìm kiếm",
    favoriteLocations = "Địa điểm yêu thích",
    pinnedCurrentLocation = "Vị trí hiện tại",
    addLocation = "Thêm vị trí",
    noFavoritesTitle = "Chưa có địa điểm yêu thích",
    noFavoritesSubtitle = "Theo dõi thời tiết nhanh chóng tại các thành phố yêu thích của bạn bằng cách nhấn Thêm vị trí.",
    feelsLike = { temp -> "Cảm giác như $temp°C" },
    feelsLikeLabel = "Cảm giác",
    humidity = "Độ ẩm",
    windSpeed = "Tốc độ gió",
    uvIndex = "Chỉ số UV",
    precipitation = "Lượng mưa",
    forecast24h = "Dự báo 24 giờ",
    forecast7d = "Dự báo 7 ngày tới",
    settingsTitle = "Cài đặt",
    languageSection = "Ngôn ngữ / Language",
    unitsAppearanceSection = "Giao diện & Đơn vị đo",
    themeMode = "Chế độ giao diện",
    themeSystem = "Hệ thống",
    themeLight = "Sáng",
    themeDark = "Tối",
    temperatureUnit = "Đơn vị nhiệt độ",
    windUnit = "Đơn vị tốc độ gió",
    updatesNotificationsSection = "Thông báo & Đồng bộ",
    dailySummary = "Tóm tắt thời tiết hàng ngày",
    dailySummaryDesc = "Nhận bản tin dự báo thời tiết sáng lúc 07:00",
    severeAlerts = "Cảnh báo thời tiết nguy hiểm",
    severeAlertsDesc = "Nhận thông báo khẩn cấp khi có bão hoặc chỉ số UV cao",
    backgroundRefresh = "Tự động làm mới trong nền",
    backgroundRefreshDesc = "Định kỳ tải dữ liệu mới nhất khi không mở app",
    offlineStorageSection = "Dữ liệu & Bộ nhớ đệm",
    offlineCache = "Bộ nhớ đệm ngoại tuyến",
    clearCache = "Xóa bộ nhớ đệm",
    clearCacheSuccess = "Đã xóa bộ nhớ đệm thành công",
    aboutSection = "Thông tin ứng dụng",
    weatherProvider = "Nguồn dữ liệu thời tiết",
    appVersion = "Phiên bản ứng dụng",
    forecastDetailTitle = { location -> "$location — Chi tiết & Xu hướng" },
    forecastSubtitle = "Chi tiết & Xu hướng",
    liveTrend = "Trực tiếp",
    sunMoonCycle = "Chu kỳ Mặt trời & Mặt trăng",
    sunrise = "Bình minh",
    solarNoon = "Giữa trưa",
    sunset = "Hoàng hôn",
    pressure = "Áp suất",
    visibility = "Tầm nhìn",
    humidityDew = "Độ ẩm & Sương",
    windGusts = "Gió & Gió giật",
    expectedToday = "Dự kiến trong ngày",
    moderate = "Trung bình",
    high = "Cao",
    normal = "Bình thường",
    standardPressure = "Áp suất tiêu chuẩn",
    clearAtmosphere = "Tầm nhìn quang đãng",
    thermalComfort = "Cảm giác nhiệt dễ chịu",
    moderateProtection = "Cần che chắn khi ra ngoài",
    dewPointLabel = { temp -> "Điểm sương: $temp°C" },
    windDirectionLabel = { deg -> "Hướng gió: $deg° Đông" }
)

val LocalAppLanguage = compositionLocalOf { AppLanguage.VIETNAMESE }
val LocalWeatherStrings = compositionLocalOf { VietnameseStrings }

@Composable
fun ProvideWeatherLanguage(
    language: AppLanguage,
    content: @Composable () -> Unit
) {
    val strings = when (language) {
        AppLanguage.VIETNAMESE -> VietnameseStrings
        AppLanguage.ENGLISH -> EnglishStrings
    }
    CompositionLocalProvider(
        LocalAppLanguage provides language,
        LocalWeatherStrings provides strings,
        content = content
    )
}
